---
apiVersion: v1
kind: Secret
metadata:
  name: gitea-credentials
  namespace: flux-system
type: Opaque
data:
  username: Z2l0ZWFfYWRtaW4=
  password: cjhzQThDUEhEOSFidDZk
  caFile: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURjekNDQWx1Z0F3SUJBZ0lRUldJaHVETnhpdWlmMHFvNjFFRWVmREFOQmdrcWhraUc5dzBCQVFzRkFEQWkKTVJBd0RnWURWUVFLRXdkQlkyMWxJRU52TVE0d0RBWURWUVFERXdWSGFYUmxZVEFlRncweU1qRXlNRGd4TnpFMQpNREZhRncweU16RXlNRGd4TnpFMU1ERmFNQ0l4RURBT0JnTlZCQW9UQjBGamJXVWdRMjh4RGpBTUJnTlZCQU1UCkJVZHBkR1ZoTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF2bGNLbUxwZkk2dGUKSUdJZVZ3amlqU3dZOFBlZkw3bDZ4SEhVRkVLY2dCbXBhSFd2L0dIbEk5WE9ORHc2QWxPR3RnNG9UZVJzM2ppdgpvb0xDWU01dWRPUWNmS283QlhHVkJ5b1ZQWDJtdjhkQTRFYm9GdW5lcWFWdk9NcFB3b1JLNWt2YkF0bms5aDBLClQyblNmUHVqWlU2eUhNTkEwRUhQVXZCbEptTkd4YzVvVkhRVzhZK1JrZ0xJOVZBekxwOGJoZ1RTMUFUbFZDL1kKUFErcXA2aHNMUmErTGxOVEtReEJSQWFsNzUxUSs5VTEzNmJEZjgzUDM3dHgyQXp4NDdOZlhYRGlqaWpYNmdnZApTY0dsU2wvY2dQamNReXZYTDBQQUQyM3BFNjdkMzcxaUVESE5FSzRDUlB4eU1WN2xadll3Mnk5bnAvalZGMVpuCjFFc0tPTGN5MHdJREFRQUJvNEdrTUlHaE1BNEdBMVVkRHdFQi93UUVBd0lDcERBVEJnTlZIU1VFRERBS0JnZ3IKQmdFRkJRY0RBVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVdCQlJpUllWbjZkZzRnN2liOElOVQpzckQ0bklEanBqQktCZ05WSFJFRVF6QkJnZ2xzYjJOaGJHaHZjM1NDSW1kcGRHVmhMV2gwZEhBdVoybDBaV0V1CmMzWmpMbU5zZFhOMFpYSXViRzlqWVd5SEJLd1NBQUtIQkt3U0FBT0hCS3dTQUFRd0RRWUpLb1pJaHZjTkFRRUwKQlFBRGdnRUJBQlh2NVNnWE9SSzhTMExOc2lDdTBvZjg1akdmMnNJRjNIcmVQUEcwd0o2KzZrbFJkTmZjMXE4cAp4TVU0NDlSdGl1Mzc2d0VpVldRS1R4RHFQWWhzOUZVQjgyQjV6U3ovaHZhUGNwMHBkeUd3UllzWmNyaEpJUDRsCmplUGhtN0RLSnhpZi9xZ0YvU1VWb2V5TTZKQlBZREt0RVg2T1k5RnF6OFlHQnpUczZTUGJjeTBSMkdOektVUE4KR0hMSmVZYVF5ZnR0aTFLNU9jT09pSEZidWdTeDlNUGl3emppejRQTXJocVg0WjJLekJSOEhvcHlWOVNabENqawpJNmJhUnh4OUwrMlhVQ0hqVUptUXNKSy9xeXFzUUF5Y3ZBMHV1Vm9JQXU3NlY4MlNMVmhnVEY4UHZpU2dEdnFnCnhDMW1nZDMydlZxZXpqak0xUW5MRkdYYzYySHFORjA9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: kratix-workload-resources
  namespace: flux-system
spec:
  interval: 5s
  url: https://172.18.0.2:31333/gitea_admin/worker-cluster-1-kratix-resources
  ref:
    branch: main
  secretRef:
    name: gitea-credentials
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kratix-workload-resources
  namespace: flux-system
spec:
  interval: 5s
  dependsOn:
    - name: kratix-workload-crds
  sourceRef:
    kind: GitRepository
    name: kratix-workload-resources
  path: "."
  prune: true
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: kratix-workload-crds
  namespace: flux-system
spec:
  interval: 5s
  url: https://172.18.0.2:31333/gitea_admin/worker-cluster-1-kratix-crds
  ref:
    branch: main
  secretRef:
    name: gitea-credentials
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kratix-workload-crds
  namespace: flux-system
spec:
  interval: 5s
  sourceRef:
    kind: GitRepository
    name: kratix-workload-crds
  path: "."
  prune: true
