apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: TBDNAME
  name: TBDNAME
  namespace: default
spec:
  selector:
    matchLabels:
      run: TBDNAME
  template:
    metadata:
      labels:
        run: TBDNAME
    spec:
      containers:
      - image: TBDIMAGE
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
        ports:
        - containerPort: 8080
        env:
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres.acid-TBDNAME-postgresql.credentials.postgresql.acid.zalan.do
                key: password
          - name: PGHOST
            value: acid-TBDNAME-postgresql.default.svc.cluster.local
          - name: DBNAME
            value: TBDNAMEdb
        imagePullPolicy: IfNotPresent
        name: TBDNAME
