---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: TBDNAME-ingress-resource-backend
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: TBDNAME.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: TBDNAME
            port:
              number: 8080
